---
#Default Profile
spring:
 application: 
  name: e-commerce-service
 output:
  ansi:
   enabled: always
databaseDriverClassName: com.mysql.cj.jdbc.Driver
databaseUrl: jdbc:mysql://localhost:3306/simple_ecommerce_db?useUnicode=yes&characterEncoding=UTF-8 
databaseUser: root
databasePassword: mosfet
hibernateDialect: org.hibernate.dialect.MySQLDialect
hibernateShowSql: false
hibernateFormatSql: true
hibernateIdNewGenerator: false 
redisHost: localhost
redisPort: 6379
redisPassword: mosfet

 
---
#Docker Profile
spring:
  profiles: docker
  application:
    name: docker
databaseDriverClassName: com.mysql.cj.jdbc.Driver
databaseUrl: jdbc:mysql://database:3306/simple_ecommerce_db?useUnicode=yes&characterEncoding=UTF-8
databaseUser: root
databasePassword: mosfet
hibernateDialect: org.hibernate.dialect.MySQLDialect
hibernateShowSql: true
hibernateFormatSql: true
hibernateIdNewGenerator: false 
redisHost: redis
redisPort: 6379
redisPassword: mosfet